<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reaction extends \App\Entity\Reaction implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'comment_id' => [parent::class, 'comment_id', null, 16],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'post_id' => [parent::class, 'post_id', null, 16],
        "\0".parent::class."\0".'travel_story_id' => [parent::class, 'travel_story_id', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'user_id' => [parent::class, 'user_id', null, 16],
        'comment_id' => [parent::class, 'comment_id', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'post_id' => [parent::class, 'post_id', null, 16],
        'travel_story_id' => [parent::class, 'travel_story_id', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'user_id' => [parent::class, 'user_id', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
