<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Preference extends \App\Entity\Preference implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'accessibilityNeeds' => [parent::class, 'accessibilityNeeds', null, 16],
        "\0".parent::class."\0".'accommodationTypes' => [parent::class, 'accommodationTypes', null, 16],
        "\0".parent::class."\0".'budgetMaxPerNight' => [parent::class, 'budgetMaxPerNight', null, 16],
        "\0".parent::class."\0".'budgetMinPerNight' => [parent::class, 'budgetMinPerNight', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'dietaryRestrictions' => [parent::class, 'dietaryRestrictions', null, 16],
        "\0".parent::class."\0".'groupType' => [parent::class, 'groupType', null, 16],
        "\0".parent::class."\0".'locationPreferences' => [parent::class, 'locationPreferences', null, 16],
        "\0".parent::class."\0".'preferenceId' => [parent::class, 'preferenceId', null, 16],
        "\0".parent::class."\0".'preferredClimate' => [parent::class, 'preferredClimate', null, 16],
        "\0".parent::class."\0".'priorities' => [parent::class, 'priorities', null, 16],
        "\0".parent::class."\0".'stylePreferences' => [parent::class, 'stylePreferences', null, 16],
        "\0".parent::class."\0".'travelPace' => [parent::class, 'travelPace', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'userId' => [parent::class, 'userId', null, 16],
        'accessibilityNeeds' => [parent::class, 'accessibilityNeeds', null, 16],
        'accommodationTypes' => [parent::class, 'accommodationTypes', null, 16],
        'budgetMaxPerNight' => [parent::class, 'budgetMaxPerNight', null, 16],
        'budgetMinPerNight' => [parent::class, 'budgetMinPerNight', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'dietaryRestrictions' => [parent::class, 'dietaryRestrictions', null, 16],
        'groupType' => [parent::class, 'groupType', null, 16],
        'locationPreferences' => [parent::class, 'locationPreferences', null, 16],
        'preferenceId' => [parent::class, 'preferenceId', null, 16],
        'preferredClimate' => [parent::class, 'preferredClimate', null, 16],
        'priorities' => [parent::class, 'priorities', null, 16],
        'stylePreferences' => [parent::class, 'stylePreferences', null, 16],
        'travelPace' => [parent::class, 'travelPace', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'userId' => [parent::class, 'userId', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
