<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TravelStory extends \App\Entity\TravelStory implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'budgetJson' => [parent::class, 'budgetJson', null, 16],
        "\0".parent::class."\0".'coverImageUrl' => [parent::class, 'coverImageUrl', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'currency' => [parent::class, 'currency', null, 16],
        "\0".parent::class."\0".'destination' => [parent::class, 'destination', null, 16],
        "\0".parent::class."\0".'destinationId' => [parent::class, 'destinationId', null, 16],
        "\0".parent::class."\0".'endDate' => [parent::class, 'endDate', null, 16],
        "\0".parent::class."\0".'favoritePlacesJson' => [parent::class, 'favoritePlacesJson', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'imageUrlsJson' => [parent::class, 'imageUrlsJson', null, 16],
        "\0".parent::class."\0".'mustDoJson' => [parent::class, 'mustDoJson', null, 16],
        "\0".parent::class."\0".'mustTryJson' => [parent::class, 'mustTryJson', null, 16],
        "\0".parent::class."\0".'mustVisitJson' => [parent::class, 'mustVisitJson', null, 16],
        "\0".parent::class."\0".'overallRating' => [parent::class, 'overallRating', null, 16],
        "\0".parent::class."\0".'removalReason' => [parent::class, 'removalReason', null, 16],
        "\0".parent::class."\0".'removedAt' => [parent::class, 'removedAt', null, 16],
        "\0".parent::class."\0".'removedByAdmin' => [parent::class, 'removedByAdmin', null, 16],
        "\0".parent::class."\0".'startDate' => [parent::class, 'startDate', null, 16],
        "\0".parent::class."\0".'summary' => [parent::class, 'summary', null, 16],
        "\0".parent::class."\0".'tagsJson' => [parent::class, 'tagsJson', null, 16],
        "\0".parent::class."\0".'tips' => [parent::class, 'tips', null, 16],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null, 16],
        "\0".parent::class."\0".'totalBudget' => [parent::class, 'totalBudget', null, 16],
        "\0".parent::class."\0".'travelStyle' => [parent::class, 'travelStyle', null, 16],
        "\0".parent::class."\0".'travelType' => [parent::class, 'travelType', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'userId' => [parent::class, 'userId', null, 16],
        "\0".parent::class."\0".'wouldGoAgain' => [parent::class, 'wouldGoAgain', null, 16],
        "\0".parent::class."\0".'wouldRecommend' => [parent::class, 'wouldRecommend', null, 16],
        'budgetJson' => [parent::class, 'budgetJson', null, 16],
        'coverImageUrl' => [parent::class, 'coverImageUrl', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'currency' => [parent::class, 'currency', null, 16],
        'destination' => [parent::class, 'destination', null, 16],
        'destinationId' => [parent::class, 'destinationId', null, 16],
        'endDate' => [parent::class, 'endDate', null, 16],
        'favoritePlacesJson' => [parent::class, 'favoritePlacesJson', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'imageUrlsJson' => [parent::class, 'imageUrlsJson', null, 16],
        'mustDoJson' => [parent::class, 'mustDoJson', null, 16],
        'mustTryJson' => [parent::class, 'mustTryJson', null, 16],
        'mustVisitJson' => [parent::class, 'mustVisitJson', null, 16],
        'overallRating' => [parent::class, 'overallRating', null, 16],
        'removalReason' => [parent::class, 'removalReason', null, 16],
        'removedAt' => [parent::class, 'removedAt', null, 16],
        'removedByAdmin' => [parent::class, 'removedByAdmin', null, 16],
        'startDate' => [parent::class, 'startDate', null, 16],
        'summary' => [parent::class, 'summary', null, 16],
        'tagsJson' => [parent::class, 'tagsJson', null, 16],
        'tips' => [parent::class, 'tips', null, 16],
        'title' => [parent::class, 'title', null, 16],
        'totalBudget' => [parent::class, 'totalBudget', null, 16],
        'travelStyle' => [parent::class, 'travelStyle', null, 16],
        'travelType' => [parent::class, 'travelType', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'userId' => [parent::class, 'userId', null, 16],
        'wouldGoAgain' => [parent::class, 'wouldGoAgain', null, 16],
        'wouldRecommend' => [parent::class, 'wouldRecommend', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
