<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Post extends \App\Entity\Post implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'body' => [parent::class, 'body', null, 16],
        "\0".parent::class."\0".'comments' => [parent::class, 'comments', null, 16],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'image_url' => [parent::class, 'image_url', null, 16],
        "\0".parent::class."\0".'is_confirmed' => [parent::class, 'is_confirmed', null, 16],
        "\0".parent::class."\0".'removal_reason' => [parent::class, 'removal_reason', null, 16],
        "\0".parent::class."\0".'removed_at' => [parent::class, 'removed_at', null, 16],
        "\0".parent::class."\0".'removed_by_admin' => [parent::class, 'removed_by_admin', null, 16],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null, 16],
        "\0".parent::class."\0".'trip_id' => [parent::class, 'trip_id', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        "\0".parent::class."\0".'user_id' => [parent::class, 'user_id', null, 16],
        'body' => [parent::class, 'body', null, 16],
        'comments' => [parent::class, 'comments', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'image_url' => [parent::class, 'image_url', null, 16],
        'is_confirmed' => [parent::class, 'is_confirmed', null, 16],
        'removal_reason' => [parent::class, 'removal_reason', null, 16],
        'removed_at' => [parent::class, 'removed_at', null, 16],
        'removed_by_admin' => [parent::class, 'removed_by_admin', null, 16],
        'title' => [parent::class, 'title', null, 16],
        'trip_id' => [parent::class, 'trip_id', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
        'user_id' => [parent::class, 'user_id', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
