<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'avatarId' => [parent::class, 'avatarId', null, 16],
        "\0".parent::class."\0".'bio' => [parent::class, 'bio', null, 16],
        "\0".parent::class."\0".'birthYear' => [parent::class, 'birthYear', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'emailVerified' => [parent::class, 'emailVerified', null, 16],
        "\0".parent::class."\0".'firstName' => [parent::class, 'firstName', null, 16],
        "\0".parent::class."\0".'gender' => [parent::class, 'gender', null, 16],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'phoneNumber' => [parent::class, 'phoneNumber', null, 16],
        "\0".parent::class."\0".'plainPassword' => [parent::class, 'plainPassword', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'userId' => [parent::class, 'userId', null, 16],
        'avatarId' => [parent::class, 'avatarId', null, 16],
        'bio' => [parent::class, 'bio', null, 16],
        'birthYear' => [parent::class, 'birthYear', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'emailVerified' => [parent::class, 'emailVerified', null, 16],
        'firstName' => [parent::class, 'firstName', null, 16],
        'gender' => [parent::class, 'gender', null, 16],
        'lastName' => [parent::class, 'lastName', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'phoneNumber' => [parent::class, 'phoneNumber', null, 16],
        'plainPassword' => [parent::class, 'plainPassword', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'userId' => [parent::class, 'userId', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
