<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Destination extends \App\Entity\Destination implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'averageRating' => [parent::class, 'averageRating', null, 16],
        "\0".parent::class."\0".'bestSeason' => [parent::class, 'bestSeason', null, 16],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null, 16],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'destinationId' => [parent::class, 'destinationId', null, 16],
        "\0".parent::class."\0".'estimatedBudget' => [parent::class, 'estimatedBudget', null, 16],
        "\0".parent::class."\0".'imageUrl' => [parent::class, 'imageUrl', null, 16],
        "\0".parent::class."\0".'latitude' => [parent::class, 'latitude', null, 16],
        "\0".parent::class."\0".'longitude' => [parent::class, 'longitude', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'popularity' => [parent::class, 'popularity', null, 16],
        "\0".parent::class."\0".'timezone' => [parent::class, 'timezone', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        'averageRating' => [parent::class, 'averageRating', null, 16],
        'bestSeason' => [parent::class, 'bestSeason', null, 16],
        'city' => [parent::class, 'city', null, 16],
        'country' => [parent::class, 'country', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'destinationId' => [parent::class, 'destinationId', null, 16],
        'estimatedBudget' => [parent::class, 'estimatedBudget', null, 16],
        'imageUrl' => [parent::class, 'imageUrl', null, 16],
        'latitude' => [parent::class, 'latitude', null, 16],
        'longitude' => [parent::class, 'longitude', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'popularity' => [parent::class, 'popularity', null, 16],
        'timezone' => [parent::class, 'timezone', null, 16],
        'type' => [parent::class, 'type', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
