<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Story extends \App\Entity\Story implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'caption' => [parent::class, 'caption', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'expiresAt' => [parent::class, 'expiresAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'imageUrl' => [parent::class, 'imageUrl', null, 16],
        "\0".parent::class."\0".'removalReason' => [parent::class, 'removalReason', null, 16],
        "\0".parent::class."\0".'removedAt' => [parent::class, 'removedAt', null, 16],
        "\0".parent::class."\0".'removedByAdmin' => [parent::class, 'removedByAdmin', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'caption' => [parent::class, 'caption', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'expiresAt' => [parent::class, 'expiresAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'imageUrl' => [parent::class, 'imageUrl', null, 16],
        'removalReason' => [parent::class, 'removalReason', null, 16],
        'removedAt' => [parent::class, 'removedAt', null, 16],
        'removedByAdmin' => [parent::class, 'removedByAdmin', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
