<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Activity extends \App\Entity\Activity implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'activityId' => [parent::class, 'activityId', null, 16],
        "\0".parent::class."\0".'ageMin' => [parent::class, 'ageMin', null, 16],
        "\0".parent::class."\0".'availableFrom' => [parent::class, 'availableFrom', null, 16],
        "\0".parent::class."\0".'availableTo' => [parent::class, 'availableTo', null, 16],
        "\0".parent::class."\0".'averageRating' => [parent::class, 'averageRating', null, 16],
        "\0".parent::class."\0".'capacity' => [parent::class, 'capacity', null, 16],
        "\0".parent::class."\0".'category' => [parent::class, 'category', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'currency' => [parent::class, 'currency', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'destination' => [parent::class, 'destination', null, 16],
        "\0".parent::class."\0".'durationMinutes' => [parent::class, 'durationMinutes', null, 16],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null, 16],
        "\0".parent::class."\0".'meetingPoint' => [parent::class, 'meetingPoint', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null, 16],
        'activityId' => [parent::class, 'activityId', null, 16],
        'ageMin' => [parent::class, 'ageMin', null, 16],
        'availableFrom' => [parent::class, 'availableFrom', null, 16],
        'availableTo' => [parent::class, 'availableTo', null, 16],
        'averageRating' => [parent::class, 'averageRating', null, 16],
        'capacity' => [parent::class, 'capacity', null, 16],
        'category' => [parent::class, 'category', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'currency' => [parent::class, 'currency', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'destination' => [parent::class, 'destination', null, 16],
        'durationMinutes' => [parent::class, 'durationMinutes', null, 16],
        'isActive' => [parent::class, 'isActive', null, 16],
        'meetingPoint' => [parent::class, 'meetingPoint', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'price' => [parent::class, 'price', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
