<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPLdvxHQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPLdvxHQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPLdvxHQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPLdvxHQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPLdvxHQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'PLdvxHQ',
    'container.build_id' => 'f1c64e33',
    'container.build_time' => 1776520849,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPLdvxHQ');
