<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFqOxKEJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFqOxKEJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFqOxKEJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFqOxKEJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFqOxKEJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'FqOxKEJ',
    'container.build_id' => 'd104af58',
    'container.build_time' => 1776289102,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFqOxKEJ');
