<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNAk4uxQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNAk4uxQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNAk4uxQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNAk4uxQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNAk4uxQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'NAk4uxQ',
    'container.build_id' => 'e0cc1f62',
    'container.build_time' => 1776433006,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNAk4uxQ');
