<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW1LkbIs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW1LkbIs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW1LkbIs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW1LkbIs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW1LkbIs\App_KernelDevDebugContainer([
    'container.build_hash' => 'W1LkbIs',
    'container.build_id' => '49c0243f',
    'container.build_time' => 1776342310,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW1LkbIs');
