<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQxn6avP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQxn6avP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQxn6avP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQxn6avP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQxn6avP\App_KernelDevDebugContainer([
    'container.build_hash' => 'Qxn6avP',
    'container.build_id' => '28d5129b',
    'container.build_time' => 1776799347,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQxn6avP');
