<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFs3zpfB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFs3zpfB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFs3zpfB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFs3zpfB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFs3zpfB\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fs3zpfB',
    'container.build_id' => '51ffe83d',
    'container.build_time' => 1776708362,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFs3zpfB');
